export enum ToolCategory {
  UNIT_TEST = 'UNIT_TEST',
  LIBRARY = 'LIBRARY',
  COMPONENT_TEST = 'COMPONENT_TEST',
  E2E_TEST = 'E2E_TEST',
  ACCESSIBILITY_TEST = 'ACCESSIBILITY_TEST',
  VISUAL_REGRESSION_TEST = 'VISUAL_REGRESSION_TEST',
  MUTATION_TEST = 'MUTATION_TEST',
}
